# pyproject.toml

[build-system]
requires      = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "proxies_scraper"
version = "0.1.0"
description = "A Python package for proxies scripting"
readme = "README.md"
authors = [
    { name="Carlosman1996", email="cmmolinas01@gmail.com" }
]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["proxies", "scripting", "networking"]
requires-python = ">=3.12"
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[project.urls]
Homepage = "https://github.com/Carlosman1996/proxies_scraper"

[tool.setuptools.packages.find]
where = [""]

# PYTEST

[tool.pytest.ini_options]
python_files = "test_*.py"
python_functions = "test_*"
addopts = "--cov-report term --cov-report xml:coverage.xml --cov=proxies_scraper --cov-fail-under=50 tests/"

# PYTEST COVERAGE

[tool.coverage.report]
skip_empty = true
exclude_also = [
    "if __name__ == .__main__.:",
]

# RUFF

[tool.ruff.lint]
select = [
    # "ALL" option enables all linters
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I"
]
ignore = ["E501"]

# ISORT

[tool.isort]
line_length = 110
known_first_party = [
	"proxies_scraper",
]

# MYPY

[tool.mypy]
exclude = "freeProxyCz.py"
