[tox]
envlist =
    clean
    py3{12}
    update-pre_commit
    style
    typing

[testenv]
description = Run the tests with pytest and generate coverage report
allowlist_externals = poetry
commands_pre =
    poetry install
skip_install = true
# Other pytest configuration is specified in project.toml file.
#   --cov-append helps to save coverage results between tox executions
commands = poetry run pytest --cov-append

[testenv:update-pre_commit]
description = Autoupdate pre-commit packages to latest versions
labels = update
commands = poetry run pre-commit autoupdate -j4

[testenv:style]
description = Run code styling using pre-commit tool
skip_install = true
commands = poetry run pre-commit run --all-files

[testenv:typing]
description = Run type checker on code base
commands = poetry run mypy proxies_scraper # TODO: enable "--strict"

[testenv:clean]
commands = poetry run coverage erase
