[tox]
envlist =
    clean
    py3{12}

[testenv]
deps =
    -r requirements.txt
    pytest
    pytest-cov
# Other pytest configuration is specified in project.toml file.
#   --cov-append helps to save coverage results between tox executions
commands = python -m pytest --cov-append



[testenv:clean]
deps = coverage
skip_install = true
commands = coverage erase
