[tox]
envlist =
    clean
    py3{12}
    update-pre_commit
    style
    typing

[testenv]
description = Run the tests with pytest and generate coverage report
deps =
    -r requirements.txt
    pytest
    pytest-cov
# Other pytest configuration is specified in project.toml file.
#   --cov-append helps to save coverage results between tox executions
commands = python -m pytest --cov-append

[testenv:update-pre_commit]
labels = update
deps = pre-commit
skip_install = true
commands = pre-commit autoupdate -j4

[testenv:style]
deps = pre-commit
skip_install = true
commands = pre-commit run --all-files

[testenv:typing]
description = Run type checker on code base
deps =
    mypy
    types-requests
    types-tabulate
    types-beautifulsoup4
commands = mypy proxies_scraper # TODO: enable "--strict"

[testenv:clean]
deps = coverage
skip_install = true
commands = coverage erase
